### ISSUE TITLE
Is there a way to bootstrap zephyr with a list of plugins to automatically install and start ?

### ISSUE THREAD

**Issue by cameronbraid** [sunshower-io/zephyr#120]
I'm looking for an automated way to bootstrap a zephyr kernel with some running plugins.

My goal is to build a oci image which during the oci entrypoint starts the kernel and installs and starts a pre-defined list of plugins

One of the pre-defined plugins will manage installation of any additional plugins that it needs (as these are installed and removed at runtime depending on the environment) 

I see there is the `zephyr-directory-scanner` plugin which may work for the initial bootstrap - however to get it running I still need to start the kernel, connect via the interactive shell, and run plugin install and start.  note: I should also point out that the `META-INF/resources/io.zephyr.api.ModuleActivator` file for this plugin is not in the jar (its in src/test/resources)

**Comment by josiahhaswell** [comment]
Currently this can be handled by
1. Installing one of the memento kernel modules by copying it into the bin or lib directories
2. Manually installing the plugins
3. Stopping the kernel 
4. Grabbing the memento.yaml file generated 

Then, in your automated process, copying that same file back to the same location. Clumsy, but I'd be happy to fix this process when I'm back next week

**Comment by cameronbraid** [comment]
thanks, I also discovered `io.zephyr.cli.Zephyr` which makes this pretty easy, however I ran in to an issue where I need to handle plugin installation failures, so I proposed a PR https://github.com/sunshower-io/zephyr/pull/121

**Comment by josiahhaswell** [comment]
I've created a discord at: [Sunshower Discord](https://discord.gg/gDsPVURw) (https://discord.gg/gDsPVURw).  Thanks for your contributions here--I'd love to make Zephyr work for your purposes so I'm setting aside some time this coming week to make that happen.

**Comment by cameronbraid** [comment]
FYI, this is no longer an issue for me given my discovery of `io.zephyr.cli.Zephyr` as I can write a simple main method to do the bootstrapping that I require
