### ISSUE TITLE
indeterminate class loading order

### ISSUE THREAD

**Issue by cameronbraid** [sunshower-io/zephyr#146]
Zephyr currently has an indeterminate class loading order (the order of jars  on the classpath differs during successive bootstraps) which leads to the following issue.

In the case where two version of the same class exist e.g. `drivenow.external.Util` two jars, sometimes the class from jar 1 is used, sometimes from jar 2.

Can zephyr switch to sorting the files in some consistent way so that the behaviour is at lease consistent ?

My findings that lead to this diagnosis is as follows :

example stacktrace extract :

```
java.lang.NoSuchMethodError: 'void drivenow.external.Util.removeTimeZoneAndMillis(javax.xml.datatype.XMLGregorianCalendar)'
    at drivenow:drivenow-webclients:46.3.0//drivenow.external.apollo.builder.AvailRequestBuilder.setPickUpDateTime(AvailRequestBuilder.java:132)
```

I setup a local zephyr that includes just this plugin and its dependencies and I wrote a small bootstrapper that uses reflection to call the static method that is not found 

```
    for (var mod : zephyr.getKernel().getModuleManager().getModules()) {
      if (mod.getCoordinate().getName().equals("drivenow-webclients")) {
        var utilClazz = mod.getClassLoader().loadClass("drivenow.external.Util");
        var xgcClazz = mod.getClassLoader().loadClass("javax.xml.datatype.XMLGregorianCalendar");
        var newXMLGregorianCalendar = utilClazz.getMethod("newXMLGregorianCalendar");
        var xgc = newXMLGregorianCalendar.invoke(null);
        System.err.println(xgc);
        var removeTimeZoneAndMillis = utilClazz.getMethod("removeTimeZoneAndMillis",  xgcClazz);
        System.err.println(removeTimeZoneAndMillis);
        removeTimeZoneAndMillis.invoke(null, xgc);
        System.err.println(xgc);

      }
    }

```

I get intermittent results, with this working some times, failing others (restarting jvm and zephyr each time)

this is what I expect, and happens some times : 
```
2021-11-08T10:50:13.512+11:00
public static void drivenow.external.Util.removeTimeZoneAndMillis(javax.xml.datatype.XMLGregorianCalendar)
2021-11-08T10:50:13
```

other times I get :

```
2021-11-08T10:51:23.233+11:00
Exception in thread "main" java.lang.NoSuchMethodException: drivenow.external.Util.removeTimeZoneAndMillis(javax.xml.datatype.XMLGregorianCalendar)
        at java.base/java.lang.Class.getMethod(Class.java:2195)
        at drivenow.webapp.zephyr.WebclientsZephyrMain.main(WebclientsZephyrMain.java:58)
```

**Comment by cameronbraid** [comment]
Using openjdk 16.0.1+9-1

**Comment by cameronbraid** [comment]
If I get the class file from the plugin
```
            var res = mod.getClassLoader().getResourceAsStream("drivenow/external/Util.class");
            Files.copy(res, Path.of("Util.class"), StandardCopyOption.REPLACE_EXISTING);
```

and decompile it using procyon the method is indeed missing.  Plus also another method has a different signature.

So I am thinking that there must be two versions of this class on the classpath and an indeterminate loading order is leading it to working sometimes and not others.

**Comment by cameronbraid** [comment]
confirmed
```
❯ for i in */*/*.jar; do if unzip -l $i| grep -q drivenow/external/Util; then echo $i; fi ; done

WEB-INF/lib/drivenow-interrent-soap-1.0.jar
WEB-INF/lib/drivenow-webclients-46.1.0.jar
```

**Comment by josiahhaswell** [comment]
Are these dependencies at the same level in the dependency graph?  The inclusion and exclusion filters might be able to help here if so.  If not, you can set export=false on the appropriate dependency so that its classpath is not re-exported to the dependent module.

**Comment by cameronbraid** [comment]
the dependencies are all at the same level - jars in a war

The issue is that two jars contain the same class.. Sometimes the class from one jar is used, sometimes the other.  All that is needed is this to be made consistent.

**Comment by josiahhaswell** [comment]
This is fixed with: https://github.com/sunshower-io/zephyr/pull/147/files

**Comment by josiahhaswell** [comment]
#147 is merged, so I'm closing this issue

**Comment by cameronbraid** [comment]
Looks good, thanks
