### ISSUE TITLE
Create Expression Language Filter API

### ISSUE THREAD

**Issue by lisagumerman** [sunshower-io/zephyr#22]
**Is your feature request related to a problem? Please describe.**
The ServiceTracker API (#9 ) requires an expression language.  OSGi only supports LDAP-style filters, but Sunshower.io has found such filters counterintuitive and less useful for our purposes.  To that end, we would like to be able to support a variety of filter languages, including LDAP, but also MVEL (https://github.com/mvel/mvel), Spring Expression Language (SPEL), etc.  These filter languages should be pluggable.

The most general-purpose API would add a Predicate filter criterion to the Service tracker, but we should also support a Query that accepts:
1. a language provider
1. an expression-language filter

and applies it to the service.

Ideally, these EL-providers should be added as plugins, rather than entrypoints or kernel modules.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Feature Checklist**
- [ ] Specification
- [ ] Implementation
- [ ] Code Review
- [ ] Unit Tests
- [ ] System Tests

**Documentation**
- [ ] Documentation Issue Reference
- [ ] Documentation

**Comment by josiahhaswell** [comment]
This is fixed in #48 -- should've been separate, but things didn't fall out that way.
